In [1]:
# !git clone https://github.com/hide-ous/semeval26_starter_pack.git

In [2]:
# !python -m pip install pandas numpy scikit-learn transformers datasets evaluate wandb

In [3]:
import json
import pandas as pd
import shutil
import os

CURRENT_DIR = os.path.abspath("")
STARTER_PACK_PATH = CURRENT_DIR + "\\semeval26_starter_pack"
DATA_PATH = CURRENT_DIR + "\\..\\data\\train_redacted.jsonl"
REHYDRATED_PATH = STARTER_PACK_PATH + "\\train_rehydrated.jsonl"
PSY_DICT_PATH = CURRENT_DIR + "\\..\\data\\psy_dict.txt"
CANDIDATE_PATH = CURRENT_DIR + "\\..\\data\\candidate_segments_for_annotation.jsonl"
DOCUMENT_PATH = CURRENT_DIR + "\\..\\data\\documents_for_annotation.jsonl"

# Dev: labels are in dev_public; text is in dev_rehydrated
DEV_PUBLIC_PATH = STARTER_PACK_PATH + "\\dev_public.jsonl"
DEV_REHYDRATED_PATH = STARTER_PACK_PATH + "\\dev_rehydrated.jsonl"

# Test: start from redacted IDs, then create a rehydrated file with text
TEST_PUBLIC_PATH = STARTER_PACK_PATH + "\\test_redacted.jsonl"
TEST_REHYDRATED_PATH = STARTER_PACK_PATH + "\\test_rehydrated.jsonl"

def load_psycomark(path=DATA_PATH):
    rows = []
    with open(path, "r", encoding="utf8") as f:
        for line in f:
            rows.append(json.loads(line))
    return pd.DataFrame(rows)

df = load_psycomark()
df.head()

,_id,conspiracy,markers,subreddit,annotator
0,t1_f7ju17o,Yes,"[{'startIndex': 8, 'endIndex': 15, 'type': 'Ev...",conspiracy,annotator_0
1,t1_k5c5yyz,Can't tell,[],HighStrangeness,annotator_1
2,t1_givys64,No,"[{'startIndex': 0, 'endIndex': 7, 'type': 'Act...",europe,annotator_2
3,t1_joq538t,Can't tell,"[{'startIndex': 0, 'endIndex': 9, 'type': 'Act...",Republican,annotator_3
4,t1_hlk1vci,No,"[{'startIndex': 96, 'endIndex': 114, 'type': '...",ForwardPartyUSA,annotator_4

In [4]:
shutil.copyfile(DATA_PATH, f"{STARTER_PACK_PATH}\\train_redacted.jsonl")

'd:\\Fac\\Fac\\MT\\psy_detectives\\notebooks\\semeval26_starter_pack\\train_redacted.jsonl'

In [5]:
%cd semeval26_starter_pack
# !python rehydrate_data.py
# Also rehydrate the competition test split (creates test_rehydrated.jsonl)
!python -c "from rehydrate_data import rehydrate_comments; rehydrate_comments('test_redacted.jsonl','test_rehydrated.jsonl')"
%cd ..

d:\Fac\Fac\MT\psy_detectives\notebooks\semeval26_starter_pack
Rehydrated data saved to 'test_rehydrated.jsonl'
d:\Fac\Fac\MT\psy_detectives\notebooks

Rehydrating comments:   0%|          | 0/2 [00:00<?, ?it/s]
Rehydrating comments:  50%|█████     | 1/2 [00:01<00:01,  1.11s/it]
Rehydrating comments: 100%|██████████| 2/2 [00:01<00:00,  1.05it/s]
Rehydrating comments: 100%|██████████| 2/2 [00:01<00:00,  1.02it/s]

In [6]:
import pandas as pd

df = pd.read_json(
    REHYDRATED_PATH,
    lines=True
)

df.head()

,_id,text,subreddit,conspiracy,markers,annotator
0,t1_f7ju17o,A great article on what's taking place in Boli...,conspiracy,Yes,"[{'startIndex': 8, 'endIndex': 15, 'type': 'Ev...",annotator_0
1,t1_k5c5yyz,Chris Lehto interviews Ashton Forbes about his...,HighStrangeness,Can't tell,[],annotator_1
2,t1_givys64,Germany has upset other EU member states by se...,europe,No,"[{'startIndex': 0, 'endIndex': 7, 'type': 'Act...",annotator_2
3,t1_joq538t,"Redditors are, just like most social media use...",Republican,Can't tell,"[{'startIndex': 0, 'endIndex': 9, 'type': 'Act...",annotator_3
4,t1_hlk1vci,u/DLWzll shared a couple days ago how the Virg...,ForwardPartyUSA,Can't tell,[],annotator_29

In [7]:
import json

with open(REHYDRATED_PATH, 'r') as f:
    first_line = json.loads(f.readline())

print(json.dumps(first_line, indent=2))

{
  "_id": "t1_f7ju17o",
  "text": "A great article on what's taking place in Bolivia, referencing some similar US backed coups in the region as well as recounting some of Bolivia's history and western policy towards the country.",
  "subreddit": "conspiracy",
  "conspiracy": "Yes",
  "markers": [
    {
      "startIndex": 8,
      "endIndex": 15,
      "type": "Evidence",
      "text": "article"
    },
    {
      "startIndex": 42,
      "endIndex": 50,
      "type": "Victim",
      "text": "Bolivia,"
    },
    {
      "startIndex": 76,
      "endIndex": 78,
      "type": "Actor",
      "text": "US"
    },
    {
      "startIndex": 86,
      "endIndex": 91,
      "type": "Action",
      "text": "coups"
    },
    {
      "startIndex": 136,
      "endIndex": 145,
      "type": "Victim",
      "text": "Bolivia's"
    }
  ],
  "annotator": "annotator_0"
}

In [8]:
# !python -m pip install -q spacy
# !python -m spacy download en_core_web_sm

In [9]:
import spacy
import re

nlp = spacy.load("en_core_web_sm")

In [10]:
def clean_text(text: str) -> str:
    text = re.sub(r"https?://\S+|www\.\S+", " <URL> ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def preprocess_row(text: str):
    cleaned = clean_text(text)
    doc = nlp(cleaned)
    sentences = [sent.text for sent in doc.sents]
    return doc, sentences

docs = []
sents = []

for t in df["text"]:
    doc, sent_list = preprocess_row(t)
    docs.append(doc)
    sents.append(sent_list)

df["spacy_doc"] = docs
df["sentences"] = sents

df[["text", "sentences"]].head(3)

,text,sentences
0,A great article on what's taking place in Boli...,[A great article on what's taking place in Bol...
1,Chris Lehto interviews Ashton Forbes about his...,[Chris Lehto interviews Ashton Forbes about hi...
2,Germany has upset other EU member states by se...,[Germany has upset other EU member states by s...

In [11]:
MODAL_LEMMAS = {"must", "should", "could", "might", "may", "would", "will", "can"}
GENERIC_AGENTS = {"elite", "elites", "government", "they", "them", "globalists", "cabal"}

def extract_candidates(doc):
    candidates = []
    for i, sent in enumerate(doc.sents):
        text = sent.text.strip()
        lemmas = [t.lemma_.lower() for t in sent]
        words_lower = [t.text.lower() for t in sent]

        has_modal = any(l in MODAL_LEMMAS for l in lemmas)
        is_question = text.endswith("?")
        has_agent = any(w in GENERIC_AGENTS for w in words_lower)

        if has_modal or is_question or has_agent:
            candidates.append({
                "sent_index": i,
                "segment": text,
                "has_modal": has_modal,
                "is_question": is_question,
                "has_agent": has_agent,
            })
    return candidates

df["candidate_segments"] = df["spacy_doc"].apply(extract_candidates)

df["candidate_segments"].iloc[0]

cand_rows = []
for _, row in df.iterrows():
    for c in row["candidate_segments"]:
        cand_rows.append({
            "_id": row["_id"],
            "conspiracy": row["conspiracy"],
            **c,
        })

candidates_df = pd.DataFrame(cand_rows)
candidates_df.head()

,_id,conspiracy,sent_index,segment,has_modal,is_question,has_agent
0,t1_k5c5yyz,Can't tell,1,They summarize all of the evidence and analysi...,False,False,True
1,t1_givys64,No,2,"However, Germany is in line to receive nearly ...",True,False,False
2,t1_joq538t,Can't tell,0,"Redditors are, just like most social media use...",False,False,True
3,t1_joq538t,Can't tell,2,Once this “license to hate” takes hold of a su...,True,False,False
4,t1_hlk1vci,Can't tell,1,This site shows the vote process round-by-roun...,True,False,False

In [12]:
import json
import re
from collections import defaultdict, Counter
import pandas as pd

token_cat_counts = defaultdict(Counter)

with open(REHYDRATED_PATH, "r", encoding="utf8") as f:
    for line in f:
        obj = json.loads(line)
        for m in obj.get("markers", []):
            mtext = m.get("text", "")
            mtype = m.get("type", None)
            if not mtype:
                continue

            tokens = [tok.lower() for tok in re.findall(r"[A-Za-z']+", mtext)]
            for tok in tokens:
                if tok:
                    token_cat_counts[tok][mtype] += 1

len(token_cat_counts)

12042

In [13]:
from collections import Counter

rows = []
for token, counter in token_cat_counts.items():
    total = sum(counter.values())
    dominant_type, dom_count = counter.most_common(1)[0]
    dominant_ratio = dom_count / total

    row = {
        "word": token,
        "total_count": total,
        "dominant_category": dominant_type,
        "dominant_ratio": dominant_ratio,
    }
    for cat in ["Actor", "Action", "Victim", "Evidence", "Threat", "Effect"]:
        row[f"{cat}_count"] = counter.get(cat, 0)
    rows.append(row)

dict_df = pd.DataFrame(rows)
dict_df.sort_values("total_count", ascending=False).head()

,word,total_count,dominant_category,dominant_ratio,Actor_count,Action_count,Victim_count,Evidence_count,Threat_count,Effect_count
28,the,3564,Evidence,0.294052,416,913,185,1048,0,1002
27,of,1955,Effect,0.317136,173,520,119,523,0,620
66,and,1780,Effect,0.289888,293,421,146,404,0,516
52,to,1773,Action,0.364354,55,646,35,420,0,617
9,a,1280,Evidence,0.310156,69,395,43,397,0,376

In [14]:
stop_like = {
    "the","a","an","of","to","and","in","on","for","is","are","was","were","be","been","being",
    "this","that","these","those","it","its","i","you","he","she","we","they","them","my","your","our",
    "at","as","by","or","if","but","from","with","so","do","does","did","have","has","had","will","would",
    "can","could","should","may","might","about","just","not","no","yes","also","there","their","than",
    "then","when","what","which","who","how","why","because","into","out","up","down","over","under"
}

filt_df = dict_df[
    (dict_df["total_count"] >= 3) &
    (dict_df["dominant_ratio"] >= 0.6) &
    (~dict_df["word"].isin(stop_like))
].copy()

filt_df.sort_values(["dominant_category","total_count"], ascending=[True, False]).head(20)

,word,total_count,dominant_category,dominant_ratio,Actor_count,Action_count,Victim_count,Evidence_count,Threat_count,Effect_count
4539,nuclear,44,Action,0.613636,0,27,1,3,0,13
2865,pushing,41,Action,0.707317,2,29,0,4,0,6
659,start,40,Action,0.800000,0,32,0,3,0,5
1820,trying,30,Action,0.666667,0,20,1,3,0,6
3697,involved,27,Action,0.703704,2,19,2,3,0,1
401,taken,25,Action,0.600000,0,15,2,4,0,4
1203,release,23,Action,0.608696,1,14,1,4,0,3
2968,cover,22,Action,0.636364,0,14,0,5,0,3
2448,doing,21,Action,0.619048,0,13,0,4,0,4
1629,shot,20,Action,0.650000,0,13,0,1,0,6
513,prevent,19,Action,0.631579,0,12,0,2,0,5
1075,taking,19,Action,0.842105,0,16,0,1,0,2
2601,hit,19,Action,0.684211,1,13,0,0,0,5
3439,goes,17,Action,0.647059,0,11,0,2,0,4
4143,posting,17,Action,0.647059,1,11,1,3,0,1
830,lies,16,Action,0.625000,1,10,1,1,0,3
2849,moving,16,Action,0.750000,0,12,0,1,0,3
3710,hidden,16,Action,0.625000,1,10,1,1,0,3
605,discuss,15,Action,0.733333,2,11,2,0,0,0
664,let,15,Action,0.600000,0,9,0,4,0,2

In [15]:
psy_dict = filt_df[["word", "dominant_category"]].rename(
    columns={"dominant_category": "category"}
)

psy_dict.to_csv(PSY_DICT_PATH, index=False)

psy_dict.head(), PSY_DICT_PATH

(              word  category
 0          article  Evidence
 13      moderators     Actor
 18            post  Evidence
 21  constitutional    Effect
 22          reform    Effect,
 'd:\\Fac\\Fac\\MT\\psy_detectives\\notebooks\\..\\data\\psy_dict.txt')

In [16]:
import csv
from collections import defaultdict, Counter

def load_psy_dict(path=PSY_DICT_PATH):
    cat2words = defaultdict(set)
    with open(path, encoding="utf8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            cat2words[row["category"]].add(row["word"].lower())
    return dict(cat2words)

cat2words = load_psy_dict()
cat2words

{'Evidence': {"'software",
  'abducted',
  'according',
  'accountable',
  'acknowledging',
  'acts',
  'ads',
  'advertised',
  'advisory',
  'airspace',
  'alive',
  'allegedly',
  'altitude',
  'amazing',
  'analysis',
  'announcement',
  'anomalous',
  'answers',
  'app',
  'appearances',
  'appearing',
  'apr',
  'arabs',
  'archive',
  'arctic',
  'argument',
  'article',
  'asinine',
  'assessments',
  'assistant',
  'association',
  'assume',
  'assumed',
  'audits',
  'august',
  'authors',
  'available',
  'baron',
  'bible',
  "billionaires'",
  'blog',
  'bloomberg',
  'bomb',
  'bombshell',
  'bond',
  'book',
  'box',
  'breaks',
  'briefing',
  'browser',
  'buddies',
  'budget',
  'burns',
  'buttress',
  'camera',
  'cant',
  'carry',
  'case',
  'centers',
  'channel',
  'charges',
  'chart',
  'check',
  'chronicle',
  'circle',
  'circles',
  'cited',
  'citing',
  'classic',
  'clip',
  'clothing',
  'clouds',
  'coincidence',
  'collective',
  'com',
  'commander',
  'committees',
  'compiling',
  'concern',
  'conclude',
  'concurrently',
  'conference',
  'confiscate',
  'consistent',
  'continually',
  'continues',
  'corona',
  'couple',
  'craft',
  'creative',
  'creators',
  'credit',
  'cristi',
  'curious',
  'data',
  'date',
  'dawn',
  'december',
  'decides',
  'decree',
  'deliver',
  'depth',
  'describing',
  'description',
  'developments',
  'dinner',
  'diplomat',
  'discovered',
  'disengagement',
  'dismiss',
  'doc',
  'documentary',
  'documentation',
  'documented',
  'documenting',
  'documents',
  'double',
  'draw',
  'draws',
  'edit',
  'edited',
  'edition',
  'editorial',
  'edits',
  'egyptian',
  'emails',
  'ended',
  'enforce',
  'england',
  'entering',
  'episode',
  'esoteric',
  'essay',
  'est',
  'estimates',
  'eventually',
  'evidence',
  'evolution',
  'example',
  'excellent',
  'excerpts',
  'execution',
  'existed',
  'experts',
  'exposes',
  'extant',
  'external',
  'facts',
  'fascinating',
  'fastest',
  'feb',
  'fiction',
  'files',
  'film',
  'filmed',
  'films',
  'firm',
  'follow',
  'footage',
  'formal',
  'founding',
  'freeman',
  'funeral',
  'garnered',
  'gas',
  'gearing',
  'geopolitics',
  'ghosts',
  'grace',
  'grievances',
  'groomed',
  'harnessed',
  'harvard',
  'headline',
  'headlines',
  'highest',
  'hired',
  'holes',
  'ice',
  'identified',
  'identifies',
  'images',
  'imagining',
  'immediately',
  'inch',
  'includes',
  'incorrect',
  'index',
  'indicate',
  'indirectly',
  'infamous',
  'informant',
  'informs',
  'initiative',
  'insights',
  'interviewed',
  'interviews',
  'intrinsic',
  'invented',
  'invoking',
  'iron',
  'italian',
  'jeremy',
  'jerusalem',
  'josh',
  'journal',
  'july',
  'jump',
  'june',
  'labeled',
  'latest',
  'leaking',
  'leaves',
  'lecture',
  'lessons',
  'letter',
  'letters',
  'liberalism',
  'lightning',
  'lights',
  'link',
  'linked',
  'links',
  'listed',
  'literature',
  'located',
  'location',
  'lovethetruth',
  'luther',
  'magazine',
  "magic'",
  'mail',
  'manifestations',
  'mansion',
  'mar',
  'march',
  'maximum',
  'medical',
  'medium',
  'melt',
  'memories',
  'mention',
  'mentioned',
  'merits',
  'metaphysics',
  'mills',
  'min',
  'mine',
  'mini',
  'minute',
  'misconceptions',
  'modem',
  'montana',
  'monuments',
  'mountain',
  'movies',
  'mps',
  'mysteriously',
  'nacreous',
  'ndaa',
  'necessities',
  'nefarious',
  'negotiated',
  'net',
  'netflix',
  'nice',
  'nonsense',
  'normal',
  'noticed',
  'obviously',
  'occult',
  'oct',
  'op',
  'org',
  'osint',
  'outrageous',
  'owen',
  'page',
  'pages',
  'paper',
  'paragraph',
  'parks',
  'parliaments',
  'particular',
  'path',
  'patrol',
  'perfectly',
  'perhaps',
  'permanent',
  'phase',
  'phil',
  'philosopher',
  'photo',
  'photographs',
  'photos',
  'picture',
  'pictured',
  'pictures',
  'pipelines',
  'placed',
  'pleaded',
  'podcast',
  'poll',
  'popularity',
  'post',
  'posted',
  'ppl',
  'premise',
  'preparatory',
  'primaries',
  'primarily',
  'probe',
  'procedure',
  'processed',
  'proof',
  'protocols',
  'proved',
  'proves',
  'provided',
  'provider',
  'quote',
  'rally',
  'random',
  'ratified',
  'realistic',
  'rebuild',
  'recent',
  'record',
  'records',
  'referenced',
  'references',
  'refusal',
  'relevant',
  'relief',
  'remember',
  'rent',
  'replies',
  'report',
  'reported',
  'reporters',
  'reports',
  'reputable',
  'required',
  'responsible',
  'reuters',
  'revelation',
  'reviews',
  'rigging',
  'roughly',
  'ryan',
  'said',
  'sales',
  'saucer',
  'saved',
  'screenshot',
  'scroll',
  'sequel',
  'settlement',
  'site',
  'six',
  'skynet',
  'sniffing',
  'software',
  'source',
  'spacecraft',
  'specifically',
  'speculation',
  'spokesman',
  'stated',
  'statement',
  'statements',
  'station',
  'story',
  'studies',
  'submission',
  'substack',
  'substantial',
  'suggests',
  'surprisingly',
  'survey',
  'symmetries',
  'tactics',
  'tale',
  'technique',
  'temporary',
  'ten',
  'terminator',
  'testimony',
  'tests',
  'text',
  'themed',
  'therefore',
  'thirty',
  'thor',
  'timeline',
  'timelines',
  'timing',
  'tool',
  'track',
  'trailer',
  'transcript',
  'transmission',
  'transparency',
  'trusts',
  'tuesday',
  'tv',
  'tweets',
  'ubi',
  'unions',
  'updated',
  'uploaded',
  'vagabond',
  'veracity',
  'verified',
  'versions',
  'vibration',
  'victoria',
  'victory',
  'video',
  'videos',
  'visited',
  'volume',
  'wall',
  'ward',
  'wastewater',
  'watched',
  'wednesday',
  'week',
  'weeks',
  'whatsoever',
  'wheel',
  'whom',
  'wiki',
  'wikipedia',
  'winning',
  "wouldn't"},
 'Actor': {'aaron',
  'abramovic',
  'actors',
  'actresses',
  'adam',
  'adams',
  'administration',
  "administration's",
  'adult',
  'advisor',
  'aeronautics',
  'agencies',
  'ailmentarius',
  'aipac',
  'airline',
  'al',
  'alefantis',
  'alt',
  'amazon',
  'amy',
  'anarchy',
  'anchor',
  'andr',
  'andrew',
  'andrews',
  'andy',
  'angeles',
  'ann',
  'anthony',
  'antidote',
  'antifa',
  'appeals',
  'apple',
  'arabia',
  'arabian',
  'archaeologists',
  'arizona',
  "army's",
  'associates',
  'attorney',
  'australian',
  'authorities',
  'aw',
  'balazs',
  'bankers',
  'banking',
  'barr',
  'basiago',
  'baudrillard',
  'beast',
  'beijing',
  'berejiklian',
  'bernie',
  'biden',
  'bielek',
  'bingo',
  'biontech',
  'blender',
  'blinken',
  'boards',
  'bob',
  'boe',
  'boris',
  'bots',
  'boyle',
  'brian',
  'brother',
  'brothers',
  'buck',
  'bureau',
  'burisch',
  'burroughs',
  'bush',
  'businessman',
  "butler's",
  'caatsa',
  'cablelabs',
  'california',
  'capitalism',
  'caption',
  'carlson',
  'cars',
  'cbs',
  'ceo',
  'cern',
  'chair',
  'chandler',
  'charles',
  'charlie',
  "china's",
  'chris',
  'christians',
  'christopher',
  'chuck',
  'cia',
  'civilization',
  'claude',
  'cleaner',
  'clinton',
  "clinton's",
  'clintons',
  'clowns',
  'codex',
  'cohen',
  'comcast',
  'comedians',
  'commanders',
  'committee',
  'conservative',
  'contractor',
  'contractors',
  'corp',
  'corporation',
  'corsi',
  'coulthart',
  'counsel',
  'countering',
  'countless',
  'crain',
  'criminals',
  'crowley',
  'dan',
  'daniel',
  'david',
  'delegates',
  'delonge',
  'democrat',
  'democrats',
  'depp',
  'deputy',
  'dershowitz',
  'desantis',
  'developers',
  'devil',
  'devious',
  'dictator',
  'dinosaur',
  'director',
  'doctors',
  'dod',
  'doj',
  'donald',
  'doordash',
  'doug',
  'douglas',
  'draconians',
  'drones',
  'dude',
  'dutch',
  'dylan',
  'ed',
  'egypt',
  'elite',
  'elizabeth',
  'ellis',
  'elon',
  'employer',
  'entin',
  'eric',
  'eve',
  'everalbum',
  'expert',
  'extraterrestrials',
  'eyewitness',
  'ezra',
  'fascists',
  'father',
  'fauci',
  'fbi',
  'fda',
  'feds',
  'feminists',
  'fighter',
  'fighters',
  'flynn',
  'forum',
  'fosta',
  'founder',
  'founders',
  'frank',
  'french',
  'frequently',
  'gabbard',
  'gala',
  'gandhi',
  'gates',
  "gates'",
  'generic',
  'georg',
  'george',
  'gerald',
  'german',
  'ghana',
  'ghislaine',
  'giants',
  'gladys',
  'globalists',
  'gmail',
  'government',
  'govt',
  'grandpa',
  'granger',
  'granny',
  'greg',
  'greta',
  'group',
  'guantanamo',
  'guru',
  'h',
  'haarp',
  'hackers',
  'hacking',
  'haddad',
  'harris',
  "he's",
  'hedges',
  'herb',
  'hillary',
  'hitler',
  'hogg',
  'holdings',
  'hollywood',
  'hooke',
  'hosts',
  'howard',
  'huerta',
  'humanoid',
  'hunter',
  'hyperborea',
  'ian',
  'ii',
  'imran',
  'inc',
  "india's",
  'indians',
  'industrial',
  'influencers',
  'inmates',
  'institute',
  'iphone',
  'iranian',
  'islamic',
  'israelis',
  'italy',
  'j',
  'jack',
  'jackson',
  'jason',
  'jean',
  'jeff',
  'jeroen',
  'jill',
  'joe',
  'jordan',
  'judges',
  'juncker',
  'justin',
  'kamala',
  'karen',
  'kellen',
  'ken',
  'kevin',
  'keyhoe',
  'kh',
  'khan',
  'klaus',
  'klein',
  'korean',
  'kushner',
  'labs',
  'lapd',
  'leaders',
  'leaker',
  'lee',
  'legacy',
  'lewinsky',
  'lgbt',
  'liberals',
  'libertarians',
  'libya',
  'liu',
  'local',
  'los',
  'ltd',
  'lund',
  'luo',
  'maga',
  'mahuta',
  'malaysian',
  'managers',
  'manby',
  'maria',
  'marina',
  'mark',
  'marko',
  'martin',
  'martini',
  'mastriano',
  'mate',
  'matt',
  'mauser',
  'max',
  'maxwell',
  'mccabe',
  'mccarthy',
  'mcconnell',
  'mcdonald',
  'md',
  'melania',
  "michael's",
  'michaels',
  'michelle',
  "michelle's",
  'michigan',
  'microsoft',
  'militant',
  'milo',
  'minister',
  'mma',
  'mod',
  'moderator',
  'moderators',
  'mods',
  'monarchies',
  'monsanto',
  'monster',
  'mormons',
  'moses',
  'mossad',
  'mother',
  'moye',
  'mr',
  'mueller',
  "mueller's",
  'musicians',
  'musk',
  'myhrvold',
  'nader',
  'napoleon',
  'narcotics',
  'nasa',
  "nasa's",
  'nathan',
  'nationals',
  'nationwide',
  'nato',
  'navy',
  'nbc',
  'neighbors',
  'neil',
  'netanyahu',
  'newsweek',
  'ngos',
  'nick',
  'nickelodeon',
  'nikola',
  'nikolas',
  'nikolic',
  'northern',
  'npr',
  'nra',
  'nsa',
  'nsw',
  'nwo',
  'nyc',
  'nyt',
  'o',
  'oligarch',
  'operatives',
  'oscar',
  'pa',
  'pacaud',
  'pakistani',
  'parenthood',
  'partners',
  'passio',
  'pastor',
  'paul',
  'pedophiles',
  'pentagon',
  'perestroika',
  'pharma',
  'pilots',
  'players',
  'poc',
  'podesta',
  'poem',
  'politico',
  'pollution',
  'polly',
  'powers',
  'premier',
  'priests',
  'prime',
  'prof',
  'prominent',
  'proponents',
  'proud',
  'province',
  'psychopaths',
  'punnet',
  'q',
  'rachel',
  'ralph',
  'ray',
  'reagan',
  'refugees',
  'register',
  'regulators',
  'reptilian',
  'researcher',
  'restaurants',
  'richard',
  'richer',
  'rivers',
  'robert',
  'rodin',
  'rogan',
  'rogue',
  'ross',
  'rothschild',
  'rothschilds',
  'rourke',
  'russian',
  'russians',
  'rwanda',
  'ryders',
  'sam',
  'sanders',
  'santa',
  'sarah',
  'satan',
  'satanic',
  'saudi',
  'schiff',
  'schumer',
  'schwabs',
  'scientology',
  'sec',
  'secretary',
  'senator',
  'senior',
  'sessions',
  'sesta',
  'seth',
  'shanghai',
  'sharia',
  'silverstein',
  'skyworks',
  'smith',
  'snopes',
  'snowflakes',
  'socialists',
  'soldier',
  'sonia',
  'soros',
  'species',
  'spitzenkandidaten',
  'sports',
  'ss',
  'starbucks',
  'steele',
  'stein',
  'steiner',
  'stephen',
  'stream',
  'student',
  'successor',
  'sudan',
  'sullivan',
  'supreme',
  'susan',
  'swim',
  'sydney',
  'tao',
  'taylor',
  'teackle',
  'tech',
  'teenager',
  'tesla',
  "they'll",
  'thompson',
  'tiktok',
  'tom',
  'tons',
  'tony',
  'toronto',
  'tplf',
  'tptb',
  'traitors',
  "trump's",
  'tsa',
  'tucker',
  'turkey',
  "twitter's",
  "uk's",
  'un',
  'unelected',
  'union',
  'vargas',
  've',
  'venezuelan',
  'vests',
  'victor',
  'virginia',
  'vladimir',
  'vloggers',
  'warner',
  'wearechange',
  'webb',
  'wef',
  'weimar',
  'weinstein',
  'wgcz',
  'whitey',
  'wildfire',
  'william',
  'xinhua',
  'yahusha',
  'yang',
  'yellow',
  'yourself',
  'zealand',
  'zelensky',
  'zhao',
  'zio',
  'zionists'},
 'Effect': {"'lockout'",
  "'pick",
  'abnormalities',
  'academic',
  'achieved',
  'acres',
  'activated',
  'activity',
  'address',
  'addressing',
  'adds',
  'advantage',
  'adverse',
  'affect',
  'afraid',
  'ages',
  'aging',
  'ahead',
  'aids',
  'airstrikes',
  'alone',
  'alter',
  'alters',
  'ammunition',
  'angles',
  'anymore',
  'appropriate',
  'approval',
  'aspects',
  'assassinated',
  'assembly',
  'assessment',
  'assumptions',
  'atari',
  'atmosphere',
  'attention',
  'authorized',
  'auto',
  'aviation',
  'avoiding',
  'awaits',
  'awhile',
  'b',
  'bad',
  'ballot',
  'baseless',
  'batteries',
  'becomes',
  'beginning',
  'behaviour',
  'belief',
  'benefit',
  'better',
  'bidding',
  'bilateral',
  'bio',
  'blew',
  'blind',
  'blood',
  'blow',
  'boomers',
  'booster',
  'boring',
  'boundaries',
  'boycotts',
  'brains',
  'brainwashed',
  'brazil',
  'breathing',
  'broken',
  'burden',
  'campaigning',
  'camps',
  'capabilities',
  'capability',
  'capitalist',
  'capture',
  'captured',
  'cardarine',
  'career',
  'carried',
  'cast',
  'catastrophe',
  'cats',
  'cave',
  'cencored',
  'cha',
  'chaff',
  'chaos',
  'cheap',
  'choose',
  'cloned',
  'clots',
  'coal',
  'collapze',
  'colony',
  'comfortable',
  'commercial',
  'concentrate',
  'conditions',
  'confused',
  'confusing',
  'considerable',
  'constitutional',
  'context',
  'continuation',
  'contracts',
  'contradictions',
  'cooperate',
  'cooperation',
  'costs',
  'count',
  "country's",
  'coup',
  'crash',
  'creates',
  'criticized',
  'critiscism',
  'crowd',
  'cures',
  'currency',
  'custody',
  'cycle',
  'danger',
  'debates',
  'debt',
  'debunk',
  'decade',
  'decide',
  'decline',
  'defensive',
  'define',
  'demand',
  'democracy',
  'democratically',
  'demographics',
  'demonstrate',
  'dependency',
  'describes',
  'desire',
  'destroy',
  'detained',
  'deterrence',
  'detrimental',
  'developing',
  'died',
  'difference',
  'different',
  'difficult',
  'dimensional',
  'disclosing',
  'discredit',
  'disgusting',
  'disorder',
  'dissociative',
  'distinct',
  'diverge',
  'diversity',
  'divided',
  'divine',
  'dogmatic',
  'done',
  'dont',
  'dose',
  'doubt',
  'drastically',
  'dropped',
  'drown',
  'dying',
  'dystopian',
  'earlier',
  "earth's",
  'easily',
  'eat',
  'effectiveness',
  'emerged',
  'emotional',
  'employed',
  'end',
  'ends',
  'endurance',
  'endure',
  'engage',
  'engagement',
  'enhance',
  'entirely',
  'entry',
  'especially',
  'establish',
  'established',
  'estate',
  'estimated',
  'evacuate',
  'evades',
  'evolutionary',
  'exactly',
  'exclusively',
  "exector's",
  'executed',
  'exercise',
  'existing',
  'expansion',
  'expect',
  'experienced',
  'experiencing',
  'explain',
  'explanations',
  'extended',
  'extra',
  'extremism',
  'fail',
  'faith',
  'fallout',
  'falls',
  'fascism',
  'fash',
  'faster',
  'feature',
  'features',
  'feeling',
  'fell',
  'feminism',
  'fill',
  'fires',
  'flanked',
  'flight',
  'flipped',
  'forcefully',
  'forcing',
  'forever',
  'forget',
  'framing',
  'frequency',
  'friendly',
  'frozen',
  'fruition',
  'fuck',
  'functions',
  'funds',
  'gain',
  'gained',
  'gaining',
  'gathering',
  'geopolitical',
  'gland',
  'glasses',
  'globally',
  'gmo',
  'gone',
  'governance',
  'greater',
  'greatly',
  'greenland',
  'grocery',
  'groundbreaking',
  'grow',
  'habitation',
  'hair',
  'harassment',
  'harm',
  'harmful',
  'haven',
  'heart',
  'heaven',
  'hedge',
  'hegemony',
  'hiding',
  'higher',
  'hire',
  'homelessness',
  'honestly',
  'hope',
  "humanity's",
  'identification',
  'identity',
  'ideological',
  'ideologically',
  'immanency',
  'immune',
  'impact',
  'impeachment',
  'implications',
  'imprisonment',
  'improvement',
  'improving',
  'inclusion',
  'income',
  'inequality',
  'infected',
  'influence',
  'injury',
  'innovation',
  'insecurity',
  'inspiration',
  'intact',
  'intellectual',
  'intelligent',
  'interested',
  'intriguing',
  'invisible',
  'jaded',
  'kinds',
  'kinetic',
  'knowing',
  'kubrick',
  'labelled',
  'lasted',
  'lay',
  'leadership',
  'leading',
  'leap',
  'learn',
  'leaving',
  'leftist',
  'less',
  'lethal',
  'limitations',
  'locked',
  'locking',
  'longer',
  'loose',
  'lose',
  'loss',
  'lung',
  'magnitude',
  'mainland',
  'maritime',
  'material',
  'mathematical',
  'matters',
  'mean',
  'meant',
  'medicines',
  'mental',
  'merely',
  'messed',
  'migrant',
  'mindset',
  'missed',
  'missing',
  'mixed',
  'modify',
  'momentum',
  'motivated',
  'multilateral',
  'murdered',
  'must',
  'myocarditis',
  'mysterious',
  'mystery',
  'nationalize',
  'navigate',
  'necessary',
  'needed',
  'needs',
  'neighboring',
  'nowadays',
  'nypd',
  "o'biden",
  'offended',
  'offer',
  'often',
  'olde',
  'olive',
  'oneness',
  'onto',
  'opportunities',
  'opportunity',
  'optimistic',
  'outcome',
  'outcomes',
  'pain',
  'paints',
  'panic',
  'paranoia',
  'partially',
  'passes',
  "paul's",
  'payments',
  'peaceful',
  "pelosi's",
  'perception',
  'performance',
  'pericarditis',
  'persists',
  'personality',
  'persuade',
  'phenomenon',
  'philosophical',
  'physically',
  'pieces',
  'pigeons',
  'pineal',
  'ploy',
  'pointing',
  'points',
  'poison',
  "poison'",
  'polio',
  'poorly',
  'pop',
  'pope',
  'pornography',
  'position',
  'positive',
  'potentially',
  'poverty',
  'precise',
  'predicted',
  'prefer',
  'preserve',
  'principle',
  'progress',
  'prohibit',
  'protecting',
  'psychological',
  'purchase',
  'pure',
  'pushback',
  'puts',
  'quantum',
  'racism',
  'radiation',
  'raids',
  'raise',
  'rapidly',
  'rapists',
  'reached',
  'reaction',
  'recovery',
  'reduce',
  'referendum',
  'reform',
  'regain',
  'religions',
  'removal',
  'remove',
  'removing',
  'repercussions',
  'replaced',
  'researched',
  'responses',
  'result',
  'resulted',
  'resulting',
  'retailer',
  'return',
  'revealing',
  'rise',
  'risk',
  'risks',
  'rival',
  'rot',
  'rotten',
  'ruin',
  'rumors',
  'satisfy',
  'scale',
  'scenes',
  'scope',
  'score',
  'screaming',
  'seek',
  'seeking',
  'sentencing',
  'seriously',
  'serves',
  'severe',
  'shady',
  'shedding',
  'shelter',
  'ships',
  'shocked',
  'sight',
  'silenced',
  'sites',
  'soft',
  'solid',
  'solve',
  'sound',
  'spectrum',
  'speeds',
  'spend',
  'sperm',
  'standards',
  'startling',
  'still',
  'stimulus',
  'stinks',
  'stones',
  'store',
  'stores',
  'straight',
  'strain',
  'strengthen',
  'strengthening',
  'stressed',
  'striking',
  'structures',
  'struggle',
  'struggling',
  'subscriptions',
  'successfully',
  'suffering',
  'sufficient',
  'suggested',
  'suicides',
  'supposed',
  'surface',
  'surprise',
  'surrounded',
  'tariffs',
  'technical',
  'terrestrial',
  'terrify',
  'terrorism',
  'terrorize',
  'texture',
  'thoughtful',
  'threats',
  'throats',
  'timey',
  'tipping',
  'total',
  'traffic',
  'tragedy',
  'transition',
  'transmit',
  'transpires',
  'trap',
  'travel',
  'tumours',
  'turn',
  'turning',
  'types',
  'uncovered',
  'underlying',
  'understand',
  'understanding',
  'understood',
  'unemployment',
  'unified',
  'unlikely',
  'urban',
  'urged',
  'usually',
  'vaccinated',
  'vague',
  'value',
  'variants',
  'vascular',
  'vast',
  'vastly',
  'vaxxed',
  'vehicles',
  'violation',
  'violently',
  'votes',
  'voyage',
  'wages',
  'wait',
  'walk',
  'walls',
  'warming',
  'wave',
  'weaken',
  'welfare',
  'wheat',
  'widespread',
  'willing',
  'witch',
  'withdrawal',
  'withheld',
  'worth',
  'wrongly',

In [17]:
from collections import Counter

def liwc_features_for_doc(doc, cat2words):
    tokens = [t.text.lower() for t in doc if not (t.is_punct or t.is_space)]
    total = len(tokens) or 1
    counter = Counter(tokens)

    feats = {}
    for cat, vocab in cat2words.items():
        count = sum(counter[w] for w in vocab)
        feats[f"{cat}_count"] = count
        feats[f"{cat}_ratio"] = count / total
    return feats

df["liwc_doc_feats"] = df["spacy_doc"].apply(lambda d: liwc_features_for_doc(d, cat2words))

liwc_doc_df = pd.json_normalize(df["liwc_doc_feats"])
doc_features_df = pd.concat([df[["_id", "conspiracy"]], liwc_doc_df], axis=1)
doc_features_df.head()

,_id,conspiracy,Evidence_count,Evidence_ratio,Actor_count,Actor_ratio,Effect_count,Effect_ratio,Action_count,Action_ratio,Victim_count,Victim_ratio
0,t1_f7ju17o,Yes,1,0.029412,0,0.000000,0,0.000000,1,0.029412,0,0.0
1,t1_k5c5yyz,Can't tell,8,0.088889,2,0.022222,3,0.033333,3,0.033333,0,0.0
2,t1_givys64,No,6,0.080000,0,0.000000,3,0.040000,3,0.040000,0,0.0
3,t1_joq538t,Can't tell,0,0.000000,2,0.028571,1,0.014286,3,0.042857,0,0.0
4,t1_hlk1vci,Can't tell,4,0.033898,1,0.008475,3,0.025424,3,0.025424,0,0.0

In [18]:
def liwc_features_for_segment(text, cat2words):
    doc = nlp(clean_text(text))
    tokens = [t.text.lower() for t in doc if not (t.is_punct or t.is_space)]
    total = len(tokens) or 1
    counter = Counter(tokens)

    feats = {}
    for cat, vocab in cat2words.items():
        count = sum(counter[w] for w in vocab)
        feats[f"{cat}_count"] = count
        feats[f"{cat}_ratio"] = count / total
    return feats

seg_rows = []
for _, row in candidates_df.iterrows():
    feats = liwc_features_for_segment(row["segment"], cat2words)
    seg_rows.append({**row, **feats})

segment_features_df = pd.DataFrame(seg_rows)
segment_features_df.head()

,_id,conspiracy,sent_index,segment,has_modal,is_question,has_agent,Evidence_count,Evidence_ratio,Actor_count,Actor_ratio,Effect_count,Effect_ratio,Action_count,Action_ratio,Victim_count,Victim_ratio
0,t1_k5c5yyz,Can't tell,1,They summarize all of the evidence and analysi...,False,False,True,4,0.137931,0,0.0,0,0.000000,3,0.103448,0,0.0
1,t1_givys64,No,2,"However, Germany is in line to receive nearly ...",True,False,False,2,0.074074,0,0.0,1,0.037037,2,0.074074,0,0.0
2,t1_joq538t,Can't tell,0,"Redditors are, just like most social media use...",False,False,True,0,0.000000,0,0.0,1,0.058824,0,0.000000,0,0.0
3,t1_joq538t,Can't tell,2,Once this “license to hate” takes hold of a su...,True,False,False,0,0.000000,0,0.0,0,0.000000,2,0.100000,0,0.0
4,t1_hlk1vci,Can't tell,1,This site shows the vote process round-by-roun...,True,False,False,2,0.071429,0,0.0,1,0.035714,1,0.035714,0,0.0

In [19]:
import json

with open(CANDIDATE_PATH, "w", encoding="utf8") as f:
    for _, row in candidates_df.iterrows():
        rec = {
            "id": f"{row['_id']}_{row['sent_index']}",
            "text": row["segment"],
            "meta": {
                "doc_id": row["_id"],
                "conspiracy": row["conspiracy"],
                "has_modal": row["has_modal"],
                "is_question": row["is_question"],
                "has_agent": row["has_agent"],
            }
        }
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")

CANDIDATE_PATH

'd:\\Fac\\Fac\\MT\\psy_detectives\\notebooks\\..\\data\\candidate_segments_for_annotation.jsonl'

In [20]:
with open(DOCUMENT_PATH, "w", encoding="utf8") as f:
    for _, row in df.iterrows():
        rec = {
            "id": row["_id"],
            "text": row["text"],
            "meta": {
                "subreddit": row.get("subreddit", None),
                "existing_conspiracy_label": row["conspiracy"],
            }
        }
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")

DOCUMENT_PATH

'd:\\Fac\\Fac\\MT\\psy_detectives\\notebooks\\..\\data\\documents_for_annotation.jsonl'

In [21]:
df[["_id", "annotator", "conspiracy"]].head()

          _id     annotator  conspiracy
0  t1_f7ju17o   annotator_0         Yes
1  t1_k5c5yyz   annotator_1  Can't tell
2  t1_givys64   annotator_2          No
3  t1_joq538t   annotator_3  Can't tell
4  t1_hlk1vci  annotator_29  Can't tell

In [22]:
from sklearn.metrics import cohen_kappa_score

pair_rows = []
for _id, group in df.groupby("_id"):
    if len(group["annotator"].unique()) == 2:
        pair_rows.append(group[["annotator", "conspiracy"]])

len(pair_rows)

0

In [23]:
a1_labels = []
a2_labels = []

for g in pair_rows:
    g_sorted = g.sort_values("annotator")
    labels = list(g_sorted["conspiracy"])
    if len(labels) == 2:
        a1_labels.append(labels[0])
        a2_labels.append(labels[1])

# cohen_kappa_score(a1_labels, a2_labels)

In [24]:
from collections import defaultdict
import numpy as np

def spans_to_charset(markers, label_type):
    chars = set()
    for m in markers:
        if m["type"] == label_type:
            start = m["startIndex"]
            end = m["endIndex"]
            chars.update(range(start, end + 1))
    return chars

def f1_for_sets(a, b):
    if not a and not b:
        return 1.0
    inter = len(a & b)
    if inter == 0:
        return 0.0
    prec = inter / (len(a) or 1)
    rec = inter / (len(b) or 1)
    if prec + rec == 0:
        return 0.0
    return 2 * prec * rec / (prec + rec)

In [25]:
label_types = ["Actor", "Action", "Evidence", "Victim", "Threat", "Effect"]

type_scores = {lt: [] for lt in label_types}

for _id, group in df.groupby("_id"):
    ann_ids = group["annotator"].unique()

    if len(ann_ids) < 2:
        continue
    
    g = group.set_index("annotator")
    ann1, ann2 = ann_ids[0], ann_ids[1]
    m1 = g.loc[ann1, "markers"]
    m2 = g.loc[ann2, "markers"]

    for lt in label_types:
        set1 = spans_to_charset(m1, lt)
        set2 = spans_to_charset(m2, lt)
        score = f1_for_sets(set1, set2)
        type_scores[lt].append(score)

span_iaa = {lt: float(np.mean(scores)) if scores else None
            for lt, scores in type_scores.items()}

span_iaa

{'Actor': None,
 'Action': None,
 'Evidence': None,
 'Victim': None,
 'Threat': None,
 'Effect': None}

### TEST

In [26]:
# If Trainer complains about accelerate, run this cell once (then restart kernel if needed).
# Keep the CUDA torch reinstall optional; it can take a while.

# !pip install --upgrade --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu130
# %pip install -q -U "accelerate>=0.26.0" transformers datasets evaluate scipy scikit-learn packaging

In [27]:
# Install Optuna for hyperparameter search
# %pip install -q -U optuna
# %pip install sentencepiece
# !pip install transformers==4.52.0 --quiet
# !pip freeze

In [28]:
def remove_uncertain_labels(batch):
    filtered_texts = []
    filtered_labels = []
    for text, label in zip(batch['text'], batch['labels']):
        norm = label.strip().lower()
        if norm in {'yes', 'no'}:
            filtered_texts.append(text)
            filtered_labels.append(label)

    return {'text': filtered_texts, 'labels': filtered_labels}

def cast_labels(batch):
    mapping = {'yes': 1, 'no': 0}
    normalized = []
    for label in batch['labels']:
        norm = label.strip().lower()
        if norm in mapping:
            normalized.append(mapping[norm])

    return {'labels': normalized}

In [29]:
# HEURISTICS
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from collections import Counter

def relabel_based_on_markers(df):
  LABEL_MAP = {'no': 0, 'yes': 1}
  new_df = df.copy()
  new_df['label_norm'] = new_df['conspiracy'].astype(str).str.strip().str.lower()

  def build_feature_vector(row):
      liwc = row.get('liwc_doc_feats')
      if not isinstance(liwc, dict):
          liwc = {}
      features = {
          'action_ratio': liwc.get('Action_ratio', 0.0),
          'evidence_ratio': liwc.get('Evidence_ratio', 0.0),
          'victim_ratio': liwc.get('Victim_ratio', 0.0),
          'effect_ratio': liwc.get('Effect_ratio', 0.0),
          'actor_ratio': liwc.get('Actor_ratio', 0.0),
          'marker_diversity': sum(1 for cat in ['Actor','Action','Victim','Evidence','Threat','Effect']
                                  if liwc.get(f'{cat}_count', 0) > 0)
      }
      return features

  feature_df = new_df.apply(build_feature_vector, axis=1, result_type='expand').fillna(0.0)
  labeled_mask = new_df['label_norm'].isin({'yes', 'no'})
  test_uncertain_mask = new_df['label_norm'] == "can't tell"
  X = feature_df[labeled_mask]
  y = new_df.loc[labeled_mask, 'label_norm'].map(LABEL_MAP)
  X_train, X_val, y_train, y_val = train_test_split(
      X, y, test_size=0.2, random_state=42, stratify=y
  )

  cal_model = LogisticRegression(max_iter=2000, C=0.5, class_weight='balanced')
  cal_model.fit(X_train, y_train)
  val_probs = cal_model.predict_proba(X_val)[:, 1]

  yes_thresh = 0.55
  no_thresh = 0.45
  uncertain_probs = cal_model.predict_proba(feature_df[test_uncertain_mask])[:, 1]
  uncertain_preds = []
  for p in uncertain_probs:
      if p >= yes_thresh:
          uncertain_preds.append('Yes')
      elif p <= no_thresh:
          uncertain_preds.append('No')
      else:
          uncertain_preds.append("Can't tell")

  print(Counter(uncertain_preds))

  new_df.loc[test_uncertain_mask, 'conspiracy'] = uncertain_preds
  return new_df

# relabel_based_on_markers(df)

In [30]:
from datasets import Dataset

def load_competition_test_data(file_path):
    """
    Loads all data from a JSONL file for inference, preserving order,
    and retaining the document's unique ID as `_id`.

    Expected fields: at least `_id` and `text`.
    """
    data = []
    with open(file_path, 'r', encoding='utf8') as f:
        for i, line in enumerate(f):
            try:
                item = json.loads(line)
                sample_id = item.get("_id", f"sample_{i}")
                data.append({
                    "_id": sample_id,
                    "text": item.get("text", "")
                })
            except json.JSONDecodeError:
                print(f"Skipping invalid JSON line at index {i} in {file_path}: {line.strip()}")
    print(f"Loaded {len(data)} samples for inference.")
    return data

# Build a DEV dataframe with *text* (dev_rehydrated) + *labels* (dev_public)
dev_text_df = pd.read_json(DEV_REHYDRATED_PATH, lines=True)
dev_labels_df = pd.read_json(DEV_PUBLIC_PATH, lines=True)[["_id", "conspiracy"]]
dev_df = dev_text_df.merge(dev_labels_df, on="_id", how="left", suffixes=("", "_label"))
dev_df["conspiracy"] = dev_df["conspiracy_label"]
dev_df["label_norm"] = dev_df["conspiracy"].astype(str).str.strip().str.lower()
dev_df = dev_df[dev_df["label_norm"].isin({"yes", "no"})].reset_index(drop=True)
print(dev_df[["_id", "conspiracy", "text"]].head(3))
print("Dev label distribution:")
print(dev_df["conspiracy"].value_counts())

# Also create a dev_dataset for inference/debugging (uses dev_rehydrated text)
dev_dataset = Dataset.from_list(load_competition_test_data(DEV_REHYDRATED_PATH))

          _id conspiracy                                               text
0  t1_f07ejkp        Yes  RFK Jr. claims that CIA operatives destroyed e...
1  t1_f6mnlr1        Yes  The next big anti trump narrative from the NWO...
2  t1_iiv2878         No  probably the most delusional article I’ve seen...
Dev label distribution:
conspiracy
No     50
Yes    27
Name: count, dtype: int64
Loaded 100 samples for inference.

In [31]:
from datasets import Dataset, DatasetDict
from sklearn.model_selection import train_test_split

LABEL_MAP = {'no': 0, 'yes': 1}
def prepare_dict(df):
    # Ensure normalized labels on the training dataframe
    if 'label_norm' not in df.columns:
        df['label_norm'] = df['conspiracy'].astype(str).str.strip().str.lower()

    usable_mask = df['label_norm'].isin({'yes', 'no'})

    # If dev_df exists, use it as the evaluation split (test_df).
    global train_df, test_df
    dev_eval_df = globals().get('dev_df', None)
    if dev_eval_df is not None:
        train_df = df[usable_mask].copy().reset_index(drop=True)
        test_df = dev_eval_df.copy().reset_index(drop=True)
    else:
        if 'train_df' not in globals() or 'test_df' not in globals():
            train_df, test_df = train_test_split(
                df[usable_mask].copy(),
                test_size=0.2,
                random_state=42,
                stratify=df.loc[usable_mask, 'label_norm']
            )
            train_df = train_df.reset_index(drop=True)
            test_df = test_df.reset_index(drop=True)

    def prepare_df_for_hf(df_in):
        # Defensive: recompute mapping and drop anything unmapped
        norm = df_in['conspiracy'].astype(str).str.strip().str.lower()
        label_id = norm.map(LABEL_MAP)
        keep = label_id.notna()
        out = pd.DataFrame()
        out['text'] = df_in.loc[keep, 'text'].astype(str)
        out['label_id'] = label_id.loc[keep].astype('int64')
        return out.reset_index(drop=True)

    train_hf = prepare_df_for_hf(train_df)
    test_hf = prepare_df_for_hf(test_df)

    dataset = DatasetDict({
        'train': Dataset.from_pandas(train_hf, preserve_index=False),
        'test': Dataset.from_pandas(test_hf, preserve_index=False)
    })

    return dataset

dataset = prepare_dict(df)
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['text', 'label_id'],
        num_rows: 3531
    })
    test: Dataset({
        features: ['text', 'label_id'],
        num_rows: 77
    })
})

In [ ]:
import os
import time
import gc
import traceback
from collections import Counter
import json
import numpy as np
import torch
from packaging import version
import optuna
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding,
    set_seed,
 )

# --- Config ---
GLOBAL_SEED = 42
set_seed(GLOBAL_SEED)

ID2LABEL = {0: "No", 1: "Yes"}
LABEL2ID = {"No": 0, "Yes": 1}

# 5 models: small -> big (incremental)
MODEL_CANDIDATES = [
    ("distilroberta", "distilroberta-base"),
    ("deberta_small", "microsoft/deberta-v3-small"),
    ("roberta_base", "roberta-base"),
    ("deberta_base", "microsoft/deberta-v3-base"),
    ("roberta_large", "roberta-large"),
    ("deberta_large", "microsoft/deberta-v3-large"),
]

TRIALS_PER_MODEL = {
    "distilroberta": 1,
    "deberta_small": 0,
    "roberta_base": 0,
    "deberta_base": 0,
    "roberta_large": 0,
    "deberta_large": 0,
}

TIMEOUT_PER_MODEL_SECONDS = {
    "distilroberta": 20 * 60,
    "deberta_small": 20 * 60,
    "roberta_base": 30 * 60,
    "deberta_base": 40 * 60,
    "roberta_large": 60 * 60,
    "deberta_large": 60 * 60,
}

def _now():
    return time.time()

def _elapsed(start_t):
    return _now() - start_t

def _compute_metrics(eval_pred):
    from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "precision": precision_score(labels, preds, average="weighted", zero_division=0),
        "recall": recall_score(labels, preds, average="weighted", zero_division=0),
        "f1": f1_score(labels, preds, average="weighted", zero_division=0),
    }

def _get_base_dataset():
    if "prepare_dict" in globals() and "df" in globals():
        base = prepare_dict(df)
    else:
        base = globals().get("dataset", None)
    if base is None:
        raise RuntimeError("No dataset found. Run the data prep cells first so `dataset` or `prepare_dict(df)` exists.")
    if "train" not in base or "test" not in base:
        raise RuntimeError("Expected a DatasetDict with keys: 'train' and 'test'.")
    for split in ["train", "test"]:
        cols = set(base[split].column_names)
        if "text" not in cols or "label_id" not in cols:
            raise RuntimeError(f"Split '{split}' missing required columns. Found: {sorted(cols)}")
    return base

def _tokenize_dataset(base_dataset, tokenizer, max_length: int):
    def tok(batch):
        return tokenizer(batch["text"], padding=False, truncation=True, max_length=max_length)
    tokenized = base_dataset.map(tok, batched=True)
    tokenized = tokenized.remove_columns(["text"])
    tokenized = tokenized.rename_column("label_id", "labels")
    return tokenized

def _is_oom_error(e: Exception) -> bool:
    msg = str(e).lower()
    return ("out of memory" in msg) or ("cuda" in msg and "memory" in msg)

def _load_tokenizer(model_name: str):
    try:
        return AutoTokenizer.from_pretrained(model_name, use_fast=True)
    except Exception as e_fast:
        print(f"Tokenizer fast load failed for {model_name}: {type(e_fast).__name__}: {str(e_fast)[:200]}")
        return AutoTokenizer.from_pretrained(model_name, use_fast=False)

best = None
best_trainer = None
best_tokenizer_name = None
best_alias = None
best_model_name = None
best_cfg = None
all_results = []

def _maybe_update_best(trainer, model_alias, model_name, cfg, metrics):
    global best, best_trainer, best_tokenizer_name, best_alias, best_model_name, best_cfg
    f1 = metrics.get("eval_f1", None)
    if f1 is None:
        return
    if best is None or f1 > best.get("eval_f1", -1):
        best = metrics
        best_trainer = trainer
        best_tokenizer_name = model_name
        best_alias = model_alias
        best_model_name = model_name
        best_cfg = cfg
        print(f"NEW BEST: {best_alias} | f1={best['eval_f1']} | cfg={best_cfg}")

def _run_optuna_for_model(model_alias: str, model_name: str):
    global all_results

    print("\n" + "=" * 90)
    print(f"OPTUNA SEARCH | model={model_alias} ({model_name})")
    print("=" * 90)

    base_dataset = _get_base_dataset()

    sampler = TPESampler(seed=GLOBAL_SEED)
    pruner = MedianPruner(n_warmup_steps=0)
    study = optuna.create_study(direction="maximize", sampler=sampler, pruner=pruner)

    def objective(trial: optuna.Trial) -> float:
        max_length = trial.suggest_categorical("max_length", [192, 256, 320, 384])
        learning_rate = trial.suggest_float("learning_rate", 3e-6, 3e-5, log=True)
        weight_decay = trial.suggest_float("weight_decay", 0.0, 0.1)
        warmup_ratio = trial.suggest_float("warmup_ratio", 0.03, 0.2)

        per_device_batch = trial.suggest_categorical("per_device_batch", [16, 24, 32, 64])
        grad_accum = trial.suggest_categorical("grad_accum", [1, 2, 4, 8])
        epochs = trial.suggest_int("epochs", 3, 6)
        gradient_checkpointing = trial.suggest_categorical("gradient_checkpointing", [False, True])
        max_steps = 400

        if model_alias in {"roberta_large", "deberta_large"}:
            max_length = 192

            learning_rate = 1e-5
            weight_decay = 0.01
            warmup_ratio = 0.06

            per_device_batch = 2
            grad_accum = 16

            epochs = 1
            gradient_checkpointing = True

        cfg = {
            "max_length": int(max_length),
            "max_steps": int(max_steps),
            "learning_rate": float(learning_rate),
            "weight_decay": float(weight_decay),
            "warmup_ratio": float(warmup_ratio),
            "per_device_batch": int(per_device_batch),
            "grad_accum": int(grad_accum),
            "epochs": int(epochs),
            "gradient_checkpointing": bool(gradient_checkpointing),
        }

        trainer = None
        model = None
        tokenizer = None
        try:
            tokenizer = _load_tokenizer(model_name)
            data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
            tokenized = _tokenize_dataset(base_dataset, tokenizer, max_length=cfg["max_length"])

            model = AutoModelForSequenceClassification.from_pretrained(
                model_name,
                num_labels=2,
                id2label=ID2LABEL,
                label2id=LABEL2ID,
            )
            if torch.cuda.is_available():
                model.to("cuda")
            if cfg["gradient_checkpointing"] and hasattr(model, "gradient_checkpointing_enable"):
                model.gradient_checkpointing_enable()

            run_tag = f"{model_alias}_t{trial.number}"
            output_dir = os.path.join(CURRENT_DIR, f"results_{run_tag}")
            log_dir = os.path.join(CURRENT_DIR, f"logs_{run_tag}")

            # Use step-based eval/save so we can cap runtime via max_steps.
            training_args = TrainingArguments(
                output_dir=output_dir,
                logging_dir=log_dir,
                per_device_train_batch_size=cfg["per_device_batch"],
                per_device_eval_batch_size=cfg["per_device_batch"],
                num_train_epochs=cfg["epochs"],
                max_steps=cfg["max_steps"],
                eval_strategy="steps",
                save_strategy="steps",
                eval_steps=100,
                save_steps=100,
                logging_steps=25,
                learning_rate=cfg["learning_rate"],
                weight_decay=cfg["weight_decay"],
                warmup_ratio=cfg["warmup_ratio"],
                lr_scheduler_type="cosine",
                optim="adamw_torch",
                gradient_accumulation_steps=cfg["grad_accum"],
                load_best_model_at_end=True,
                metric_for_best_model="f1",
                greater_is_better=True,
                save_total_limit=1,
                fp16=torch.cuda.is_available(),
                report_to="none",
                seed=GLOBAL_SEED,
                data_seed=GLOBAL_SEED,
            )

            trainer = Trainer(
                model=model,
                args=training_args,
                train_dataset=tokenized["train"],
                eval_dataset=tokenized["test"],
                tokenizer=tokenizer,
                data_collator=data_collator,
                compute_metrics=_compute_metrics,
            )

            t0 = _now()
            trainer.train()
            train_seconds = _now() - t0
            metrics = trainer.evaluate()
            metrics = {k: (float(v) if isinstance(v, (np.floating, np.integer)) else v) for k, v in metrics.items()}
            metrics.update({
                "status": "ok",
                "train_seconds": float(train_seconds),
                "model_alias": model_alias,
                "model_name": model_name,
                "cfg": cfg,
                "trial_number": int(trial.number),
            })
            all_results.append(metrics)

            f1 = metrics.get("eval_f1", -1.0)
            trial.set_user_attr("eval_f1", float(f1))
            trial.set_user_attr("train_seconds", float(train_seconds))
            trial.set_user_attr("status", "ok")

            _maybe_update_best(trainer, model_alias, model_name, cfg, metrics)
            return float(f1)
        except Exception as e:
            status = "oom" if _is_oom_error(e) else "error"
            if status == "oom" and torch.cuda.is_available():
                torch.cuda.empty_cache()
            trial.set_user_attr("status", status)
            trial.set_user_attr("error", str(e)[:2000])
            all_results.append({
                "status": status,
                "model_alias": model_alias,
                "model_name": model_name,
                "cfg": cfg,
                "error": str(e),
            })
            return -1.0
        finally:
            try:
                if trainer is not None and trainer is not best_trainer:
                    del trainer
                if model is not None and (best_trainer is None or model is not getattr(best_trainer, 'model', None)):
                    del model
            except Exception:
                pass
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    n_trials = int(TRIALS_PER_MODEL.get(model_alias, 3))
    timeout = TIMEOUT_PER_MODEL_SECONDS.get(model_alias, 20 * 60)
    if timeout <= 0 or n_trials <= 0:
        print(f"Skipping {model_alias}: n_trials={n_trials}, timeout={timeout}s")
        return

    print(f"Optuna settings: n_trials={n_trials}, timeout={timeout}s")
    try:
        study.optimize(objective, n_trials=n_trials, timeout=timeout, gc_after_trial=True, show_progress_bar=False)
    except Exception:
        print("Optuna optimize() ended with an exception (continuing to next model):")
        traceback.print_exc()

    best_trial = study.best_trial if len(study.trials) else None
    if best_trial is not None:
        print(f"Best trial for {model_alias}: value={best_trial.value} params={best_trial.params}")
    else:
        print(f"No successful trials for {model_alias}.")

for model_alias, model_name in MODEL_CANDIDATES:
    _run_optuna_for_model(model_alias, model_name)

print("\n" + "#" * 90)
print("SEARCH SUMMARY")
print("#" * 90)
ok_runs = [r for r in all_results if r.get("status") == "ok"]
fail_runs = [r for r in all_results if r.get("status") != "ok"]
print(f"Total trials recorded: {len(all_results)} | ok: {len(ok_runs)} | failed/oom: {len(fail_runs)}")

if best is None:
    print("No successful runs. Check errors above (install accelerate/optuna, reduce model sizes, or shorten max_length).")
else:
    print("\nBEST MODEL")
    print(f"- alias: {best_alias}")
    print(f"- model_name: {best_model_name}")
    print(f"- eval_f1: {best.get('eval_f1')}")
    print(f"- config: {best_cfg}")

    if "dev_dataset" in globals() and best_trainer is not None:
        best_tokenizer = _load_tokenizer(best_tokenizer_name)
        def tok_dev(batch):
            return best_tokenizer(batch["text"], padding=False, truncation=True, max_length=best_cfg["max_length"])
        tokenized_dev_dataset = dev_dataset.map(tok_dev, batched=True)
        tokenized_dev_dataset = tokenized_dev_dataset.remove_columns(["text", "_id"]) if "_id" in tokenized_dev_dataset.column_names else tokenized_dev_dataset.remove_columns(["text"])
        dev_out = best_trainer.predict(tokenized_dev_dataset)
        dev_pred_ids = np.argmax(dev_out.predictions, axis=-1)
        dev_predicted_labels = [ID2LABEL[int(i)] for i in dev_pred_ids]
        print("\nDev prediction distribution (best model):")
        print(Counter(dev_predicted_labels))

trained_models = {}
if best is not None:
    trained_models[best_alias] = {
        "trainer": best_trainer,
        "tokenizer": _load_tokenizer(best_tokenizer_name),
        "model_name": best_model_name,
        "cfg": best_cfg,
        "metrics": best,
    }

[I 2026-01-20 08:16:43,406] A new study created in memory with name: no-name-6983396c-f4a7-44ec-9892-2517b27e62c4

==========================================================================================
OPTUNA SEARCH | model=distilroberta (distilroberta-base)
==========================================================================================
Optuna settings: n_trials=1, timeout=1200s

Map:   0%|          | 0/3531 [00:00<?, ? examples/s]

Map:   0%|          | 0/77 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at distilroberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\lucian.isac\AppData\Local\Temp\ipykernel_3212\263838936.py:233: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2026-01-20 08:17:45,866] Trial 0 finished with value: 0.7198515769944341 and parameters: {'max_length': 256, 'learning_rate': 4.296748115469074e-06, 'weight_decay': 0.015599452033620266, 'warmup_ratio': 0.039874214068593906, 'per_device_batch': 16, 'grad_accum': 1, 'epochs': 3, 'gradient_checkpointing': True}. Best is trial 0 with value: 0.7198515769944341.

NEW BEST: distilroberta | f1=0.7198515769944341 | cfg={'max_length': 256, 'max_steps': 400, 'learning_rate': 4.296748115469074e-06, 'weight_decay': 0.015599452033620266, 'warmup_ratio': 0.039874214068593906, 'per_device_batch': 16, 'grad_accum': 1, 'epochs': 3, 'gradient_checkpointing': True}
Best trial for distilroberta: value=0.7198515769944341 params={'max_length': 256, 'learning_rate': 4.296748115469074e-06, 'weight_decay': 0.015599452033620266, 'warmup_ratio': 0.039874214068593906, 'per_device_batch': 16, 'grad_accum': 1, 'epochs': 3, 'gradient_checkpointing': True}

==========================================================================================
OPTUNA SEARCH | model=deberta_small (microsoft/deberta-v3-small)
==========================================================================================

[I 2026-01-20 08:17:46,021] A new study created in memory with name: no-name-1cada244-d16b-40b2-ae73-c91b3d6fb311
[I 2026-01-20 08:17:46,036] A new study created in memory with name: no-name-f984740a-68d4-4f27-af39-28cb71ad1cf9
[I 2026-01-20 08:17:46,057] A new study created in memory with name: no-name-f5759691-22f5-4352-af1f-1ba05b9ba7ea
[I 2026-01-20 08:17:46,069] A new study created in memory with name: no-name-ce066f86-dd13-4aaf-b6d0-2b29a6113fbe
[I 2026-01-20 08:17:46,086] A new study created in memory with name: no-name-411ad840-d68a-45b6-ace5-63e8317b8fde

Skipping deberta_small: n_trials=0, timeout=1200s

==========================================================================================
OPTUNA SEARCH | model=roberta_base (roberta-base)
==========================================================================================
Skipping roberta_base: n_trials=0, timeout=1800s

==========================================================================================
OPTUNA SEARCH | model=deberta_base (microsoft/deberta-v3-base)
==========================================================================================
Skipping deberta_base: n_trials=0, timeout=2400s

==========================================================================================
OPTUNA SEARCH | model=roberta_large (roberta-large)
==========================================================================================
Skipping roberta_large: n_trials=0, timeout=3600s

==========================================================================================
OPTUNA SEARCH | model=deberta_large (microsoft/deberta-v3-large)
==========================================================================================
Skipping deberta_large: n_trials=0, timeout=3600s

##########################################################################################
SEARCH SUMMARY
##########################################################################################
Total trials recorded: 1 | ok: 1 | failed/oom: 0

BEST MODEL
- alias: distilroberta
- model_name: distilroberta-base
- eval_f1: 0.7198515769944341
- config: {'max_length': 256, 'max_steps': 400, 'learning_rate': 4.296748115469074e-06, 'weight_decay': 0.015599452033620266, 'warmup_ratio': 0.039874214068593906, 'per_device_batch': 16, 'grad_accum': 1, 'epochs': 3, 'gradient_checkpointing': True}

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Dev prediction distribution (best model):
Counter({'No': 70, 'Yes': 30})

In [ ]:
# BEST CONFIG PER MODEL (run after the Optuna search cell)
import os
import json
import pandas as pd

if "all_results" not in globals():
    raise RuntimeError("`all_results` not found. Run the Optuna search cell first.")

def best_run_for_model(model_alias: str):
    runs = [r for r in all_results if r.get("status") == "ok" and r.get("model_alias") == model_alias]
    if not runs:
        return None
    return max(runs, key=lambda r: float(r.get("eval_f1", -1.0)))

rows = []
for model_alias, model_name in MODEL_CANDIDATES:
    best_run = best_run_for_model(model_alias)
    if best_run is None:
        rows.append({
            "model_alias": model_alias,
            "model_name": model_name,
            "eval_f1": None,
            "trial_number": None,
        })
        continue
    cfg = best_run.get("cfg", {}) or {}
    row = {
        "model_alias": model_alias,
        "model_name": best_run.get("model_name", model_name),
        "eval_f1": float(best_run.get("eval_f1")),
        "trial_number": best_run.get("trial_number"),
    }
    # also expand cfg into separate columns for easy sorting/filtering
    for k, v in cfg.items():
        row[str(k)] = v
    rows.append(row)

best_per_model_df = pd.DataFrame(rows)
out_path = os.path.join(CURRENT_DIR, "best_config_per_model.csv")
best_per_model_df.to_csv(out_path, index=False)
print(f"Wrote: {out_path}")
best_per_model_df.sort_values("eval_f1", ascending=False, na_position="last")

Wrote: d:\Fac\Fac\MT\psy_detectives\notebooks\best_config_per_model.csv

,model_alias,model_name,eval_f1,trial_number,max_length,max_steps,learning_rate,weight_decay,warmup_ratio,per_device_batch,grad_accum,epochs,gradient_checkpointing
5,deberta_large,microsoft/deberta-v3-large,0.83388,0.0,192.0,400.0,0.00001,0.01,0.06,2.0,16.0,1.0,True
4,roberta_large,roberta-large,0.76403,0.0,192.0,400.0,0.00001,0.01,0.06,2.0,16.0,1.0,True
0,distilroberta,distilroberta-base,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,deberta_small,microsoft/deberta-v3-small,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,roberta_base,roberta-base,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,deberta_base,microsoft/deberta-v3-base,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# TEST (REHYDRATED) SUBMISSION JSONL (run after training/search + after rehydration step)
import os
import json
import numpy as np
from datasets import Dataset

# Load rehydrated test (must contain `_id` + `text`)
test_dataset = Dataset.from_list(load_competition_test_data(TEST_REHYDRATED_PATH))
print(test_dataset)

if not isinstance(trained_models, dict) or len(trained_models) == 0:
    raise RuntimeError("No trained model found. Run the model search/training cell first.")

# Use the best model stored in trained_models (it contains exactly one entry: the best run)
best_alias = next(iter(trained_models.keys()))
pack = trained_models[best_alias]
trainer = pack["trainer"]
tokenizer = pack["tokenizer"]
cfg = pack.get("cfg", {"max_length": 256})
max_length = int(cfg.get("max_length", 256))

def tokenize_batch(batch):
    return tokenizer(batch['text'], padding=False, truncation=True, max_length=max_length)

tokenized_test_dataset = test_dataset.map(tokenize_batch, batched=True)
tokenized_test_dataset = tokenized_test_dataset.remove_columns(["text", "_id"])
predictions_output = trainer.predict(tokenized_test_dataset)

logits = predictions_output.predictions
predicted_class_ids = np.argmax(logits, axis=-1)
predicted_labels = [ID2LABEL[int(i)] for i in predicted_class_ids]
ids = test_dataset["_id"]

out_path = os.path.join(CURRENT_DIR, f"submission_{best_alias}.jsonl")
with open(out_path, 'w', encoding='utf8') as f:
    for i, label in enumerate(predicted_labels):
        f.write(json.dumps({"_id": ids[i], "conspiracy": label}, ensure_ascii=False) + "\n")

print(f"Wrote submission file (best model={best_alias}): {out_path}")

Loaded 938 samples for inference.
Dataset({
    features: ['_id', 'text'],
    num_rows: 938
})

Map:   0%|          | 0/938 [00:00<?, ? examples/s]

Wrote submission file (best model=deberta_large): d:\Fac\Fac\MT\psy_detectives\notebooks\submission_deberta_large.jsonl